### ISSUE TITLE
Bulwark-Qt 1.0.2.3 Crashing on startup (macOS 10.13.2)

### ISSUE THREAD

**Issue by kewagi** [bulwark-crypto/Bulwark#11]
Bulwark-Qt, starts, but then crashes almost every time when the loading screen says "Done loading". Here is a  [Gist](https://gist.github.com/kewagi/ea9098d30565b6c50259ae5d7fb4c9c3) of the crash report.

**Comment by chaiwatmat** [comment]
Me too.

**Comment by bulwark-crypto** [comment]
@chaiwatmat Are you running High Sierra as well?

**Comment by chaiwatmat** [comment]
@bulwark-crypto Yes, I am.

macOS High Sierra
Version 10.13.2 (17C88)

**Comment by ElMatella** [comment]
I've got the same problem here

**Comment by huglester** [comment]
same problem. high sierra

**Comment by aragalie** [comment]
+1

**Comment by kewagi** [comment]
Between Sierra and High Sierra, Apple switched from OpenSSL to LibreSSL - could this be the reason for all those problems?

**Comment by orpenk** [comment]
is there any ETA for the fix?

**Comment by kewagi** [comment]
This problem will be fixed in the next version.
