### ISSUE TITLE
Crashes on OSX Mojave 10.14.1 on startup and corrupts the database

### ISSUE THREAD

**Issue by mandica** [bulwark-crypto/Bulwark#126]
The client 2.0 crashes on startup on Mac and will not run again. This problem is new and did not occur previously when I was running the client.

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
Assertion failed: (!pthread_mutex_lock(&m)), function lock, file /usr/local/include/boost/thread/pthread/recursive_mutex.hpp, line 110.

<img width="451" alt="screenshot 2018-11-06 at 04 15 08" src="https://user-images.githubusercontent.com/42620925/48042754-04a5c580-e17b-11e8-852b-9162e79fa951.png">

**Comment by kewagi** [comment]
Hi there! This error means your local data storage is corrupted. Try resyncing the wallet by following the "old" way in [this guide](https://kb.bulwarkcrypto.com/Guides/Wallet-Syncing-Issues/), if this doesn't help your wallet is damaged and you need to restore a backup. 

If you do not have a recent backup of your wallet, you can find one in the folder  
 _~/Library/Application Support/Bulwark/backups/_

**Comment by dustinengle** [comment]
Better error handling has been added to catch QT errors that are causing corruption.  Will be in next release but if the problem persists after version 2.1.0.0 please post a debug.log after the crash as well, that will provide more Bulwark specific information.  

Thanks again.
