### ISSUE TITLE
bulwark-qt segfaults on macOS after encrypting wallet

### ISSUE THREAD

**Issue by kewagi** [bulwark-crypto/Bulwark#13]
Since the Bulwark app is currently broken, I downloaded  bulwark-1.2.0.3-x86_64-apple-darwin11.tar.gz and tried to see if I could get it to work. bulwark-qt from this tarball runs fine on High Sierra, and everything worked well until I encrypted my wallet. Encryption went through, the client said it had to restart, and when I tried to start bulwark-qt again, I get

`Segmentation fault: 11`

Here's a [gist](https://gist.github.com/kewagi/8ff1bbfbedb13a0b23328e5ca7284515) of the crash report.

**Comment by huglester** [comment]
for me it started after install.
started downloading osmething... and now I get:
Bulwark Core quit unexpectedly.

**Comment by ian** [comment]
Same, here's output: 

```
➜  bin ./bulwark-qt
[1]    6623 segmentation fault  ./bulwark-qt
```

**Comment by orpenk** [comment]
is there any ETA for the fix?

**Comment by kewagi** [comment]
This problem will be fixed in the next version.
