### ISSUE TITLE
Build unix issue

### ISSUE THREAD

**Issue by Z1gun** [bulwark-crypto/Bulwark#14]
Any suggest? 

> CXX      libbitcoin_server_a-init.o
> g++: internal compiler error: Killed (program cc1plus)

OS: Ubuntu 16.04

**Comment by heartofgold42** [comment]
You are low on memory and probably don't have a swap file (or a large enough swap file) set up. Do something along the lines of

```
fallocate -l 2G /mnt/swap
mkswap /mnt/swap
swapon /mnt/swap
```

**Comment by kewagi** [comment]
Hasn't been commented on in over a month, closing.
