### ISSUE TITLE
Masternode goes to MISSING status. 

### ISSUE THREAD

**Issue by ECB9188** [bulwark-crypto/Bulwark#146]
My node has been working good for a long time, but lately it has been going to Missing and refreshing does not solve the issue. I have got the debug log file that I will paste a link here so you can take a look at. Please, attend to this issue and help resolve it. Seems some users are facing the exact same problem. 

https://transfer.sh/11Oseu/debug.log

**Comment by eyazz34** [comment]
Same issue here.
https://transfer.sh/15yHnB/debug.log

**Comment by dustinengle** [comment]
11Oseu:
`ERROR: VerifyDB() : *** irrecoverable inconsistency in block data at 343835, hash=cec326c6e4163d196594eebe966fb9a97f9aa6083a6c67916706f160ed8442f7`

15yHnB:
`ERROR: VerifyDB() : *** irrecoverable inconsistency in block data at 348113, hash=079aff25df0da1c5e5dcf5e751182634891c72d55dbaaf274cd5fb63d79fbe08`

**Comment by eyazz34** [comment]
> 11Oseu:
> `ERROR: VerifyDB() : *** irrecoverable inconsistency in block data at 343835, hash=cec326c6e4163d196594eebe966fb9a97f9aa6083a6c67916706f160ed8442f7`
> 
> 15yHnB:
> `ERROR: VerifyDB() : *** irrecoverable inconsistency in block data at 348113, hash=079aff25df0da1c5e5dcf5e751182634891c72d55dbaaf274cd5fb63d79fbe08`

How can we resolve this error ?

**Comment by KaneoHunter** [comment]
@eyazz34 @ECB9188 

Have you attempted following the below?

https://kb.bulwarkcrypto.com/Guides/Refresh-Guide/

**Comment by eyazz34** [comment]
Yes I dit but it didn't work, my MN is still missing

**Comment by dustinengle** [comment]
We are able to duplicate the behavior and have made some changes that fix the corruption during testing. Fix will be in the next release.

**Comment by dustinengle** [comment]
Yes, we will be releasing v2.1.0.0 within the next 24hrs.

**Comment by eyazz34** [comment]
My debug.log with the new wallet (2.1.1)
https://transfer.sh/1W3It/debug.log

**Comment by ECB9188** [comment]
The node keeps crashing. I have tried to refresh, but it works for a limited time before it goes to Missing again, seems like the daemon stops. Debug log is here ->> https://transfer.sh/jIQJC/debug.log

**Comment by VoxTerra77** [comment]
**Please include the following information when submitting a log**

Copy/paste this in to your comment and fill it out with all relevant information. This will greatly assist us in finding the possible source of whatever may be causing instability.
```
**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Wallet Version [e.g. 2.0.0]

**VPS Details (please complete the following information):**
- Provider: [e.g. Vultr, Masterhash, GIN]
- OS: [e.g. Ubuntu Linux 16.04]
 - Wallet Version [e.g. 2.0.0]
 - RAM quantity
 - CPU cores

**Please run the following commands and provide the outputs**
 - `free -m`
 - `dmesg | egrep -i 'killed process'`

 -
 -
```

**Comment by ECB9188** [comment]
**Desktop:**
 - OS: Windows 10 64 bit
 - Wallet Version 2.1.1.

**VPS Details (please complete the following information):**
- Provider: Vultr
- OS: Linux Ubuntu 16.04 x64
 - Wallet Version 2.1.1.
 - RAM quantity - 1024 MB
 - CPU cores - 1 vCore

**Please run the following commands and provide the outputs**
 - `free -m`
              total        used        free      shared  buff/cache   available
Mem:            992         826          82           8          82          43
Swap:             0           0           0

 - `dmesg | egrep -i 'killed process'`
>

**Comment by blockmover** [comment]
I do have the same issue with multiple of my nodes; some are working just fine some are went missing after a short time (all with the new version) the nodes with the old sw version are just running fine. The OS and setup seems to be ok. 
Any news on that issue?

**Comment by VoxTerra77** [comment]
> 
> 
> I do have the same issue with multiple of my nodes; some are working just fine some are went missing after a short time (all with the new version) the nodes with the old sw version are just running fine. The OS and setup seems to be ok.
> Any news on that issue?

Can you please fill out the information requested 4 messages above? Its an issue we're looking in to but are still attempting to replicate, so all the information we can gather is extremely helpful.

**Comment by eyazz34** [comment]
Desktop:

OS: Mac OSx 10.14.2
Wallet Version 2.1.1

VPS Details :

Provider: Vultr
OS: Linux Ubuntu 16.04 x64
Wallet Version 2.1.1.
RAM quantity - 1024 MB
CPU cores - 1 vCore

Please run the following commands and provide the outputs :

free -m
total used free shared buff/cache available
Mem:            992         853          63          10          75          18
Swap:             0           0           0

dmesg | egrep -i 'killed process'

**Comment by blockmover** [comment]
Desktop:

Provider: Contabo
OS: Linux Ubuntu 18.04.01 x64
Wallet Version 2.1.1
RAM quantity - 30 GB
CPU cores - 8 Cores
Please run the following commands and provide the outputs

free -m
              total        used        free      shared  buff/cache   available
Mem:          24104       11259       10770           1        2073       12476
Swap:          2047           0        2047

dmesg | egrep -i 'killed process'

debug.log file is here
https://transfer.sh/10dDtv/debug.log
