### ISSUE TITLE
QT wallet stucks at block 199 on starting in MacOS Mojave

### ISSUE THREAD

**Issue by guggi0990** [bulwark-crypto/Bulwark#154]
Hi
Whenever i am opening the QT wallet on my MacOS Mojave, the wallet gets stuck at 199 blocks and then i have to delete the files in Bulwark folder and resync from 0 blocks.

i have been facing this issue from last month. Before, this issue was coming sometimes, but now every time i open the wallet, it just gets stuck at 199th block.
Please find the below screenshot and debug.log file.

![bwk stuck 199](https://user-images.githubusercontent.com/36996502/50467757-afdc3980-09ca-11e9-99e0-f22d0946dfb0.jpg)

https://transfer.sh/cAVFa/debug.log

Thank you.
Peace

**Comment by dustinengle** [comment]
@guggi0990 Try this:
1. Shutdown the Bulwark wallet.
2. Browse to the data directory https://kb.bulwarkcrypto.com/Guides/AppData-Guide/
3. Remove everything **EXCEPT** `backup/`, `wallet.dat`, `masternode.conf`, and `bulwark.conf` from the folder.  If any of the listed items are missing that should be ok as long as the `wallet.dat` is there, this "holds" your BWK essentially, it should always be there, and never be deleted.
4. Download the bootstrap file https://kb.bulwarkcrypto.com/Information/Bootstrap/ and unzip the `bootstrap.dat` file into the data directory.  After this step, there should be max 5 items in the data directory, the bootstrap file and the file(s) from step 3.
5. Start the wallet.  It should start to sync and will sync faster with the bootstrap file.
