### ISSUE TITLE
Assertion failed!

### ISSUE THREAD

**Issue by DeigonQQ** [bulwark-crypto/Bulwark#16]
Every time i try to open the wallet I get this error.

Assertion Failed!
Program: D:\bulwark-1.2.0 wallet\bin\bulwark-qt.exe
File: main.cpp, Line2871

Expression: !setBlockIndexCandidates.empty()

**Comment by vitalybond** [comment]
I have the same Alert, only with ignore is opened the wallet but sink with network failed. 
this Alert without sync over 2 days.
I mining to my wallet and now I don't know what about my deposit to my wallet.

**Comment by lsamayoa** [comment]
@vitalybond I would suggest backing up your actual `wallet.dat` it is usually stored in `%APPDATA%\Bulwark` then clearing up all the blockchain data and resync the whole blockchain. Not sure what is causing this issue but at least you would be able to get your mined coins.

So what I would do is:
1. Copy and store in a secure place your `wallet.dat`
2. Then rename the bulwark application data folder freom `%APPDATA%\Bulwark` to `%APPDATA%\Bulwark.bkp`
3. Relaunch `bulwark-qt`

**Comment by vitalybond** [comment]
Thank you very much.
this work.
Thanks.
Regards Vitaly.
