### ISSUE TITLE
Have wallet go through soft-close procedure when force closing

### ISSUE THREAD

**Issue by VoxTerra77** [bulwark-crypto/Bulwark#160]
*Adding at request of a user*

**Is your feature request related to a problem? Please describe.**
When I shut down my PC without soft-closing my wallet, the chaindata almost always corrupts. 

**Describe the solution you'd like**
When I initiate a shutdown in windows, have the wallet go through its soft-close procedure like every other windows program.

**Describe alternatives you've considered**
N/A

**Additional context**
N/a

**Comment by padraiq** [comment]
This issue was moved to https://community.bulwarkcrypto.com/t/have-wallet-go-through-soft-close-procedure-when-force-closing/155

**Comment by dustinengle** [comment]
You should never just shut down Windows without closing the open applications.  This can cause corruption on so many different levels.  This is a common understanding since Bitcoin that you should always close the wallet before turning off the computer.  Doing this is asking for issues.
