### ISSUE TITLE
Intego Virus Protection Identifies Bulwark.Qt as OSXMiner.Qt Malware

### ISSUE THREAD

**Issue by nunyabiddensss** [bulwark-crypto/Bulwark#163]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to resolve Intego Virus Barrier Issue so that know whether Bulwark.Qt is mining on my desktop.

### Description

I received email notification from INtego that Bulwark.Qt is identified as a malware, ans OSXMiner.qt.

I downloaded from here and so I labeled the file as TRUST.
I am using the GIN Platform to run Bulwark as a masternode. 
The wallet loads and syncs, although at times, the masternode status shows as "MISSING" - otherwise wallet appears to function normally.

*Summary*: If you would be able to advise whether Bulwark.Qt is mining in the background on my desktop. Ideally, it would be good if someone could advise Intego that Bulwark.Qt is not malware but benefitware.

Many thanks,

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Bulwark version: Bulwark Core 2.1.0
[comment]: # (Windows, MacOS or Linux.)
* Operating System: MacOSX - High Sierra 10.13.6

![screen shot 2019-01-10 at 12 13 01 pm](https://user-images.githubusercontent.com/29241070/50940200-15085280-14d4-11e9-96a3-ad98fbc4948a.png)

[comment]:
```
...
```

**Comment by dustinengle** [comment]
@nunyabiddensss The miner in the Qt wallet provides CPU mining, which is used in testing and when the blockchain first started before GPUs and eventually ASICs joined.  The same CPU miner is what stakes and is why the wallet must be open and unlocked in order for it to run and staking to happen.  

There is no malicious code in the wallet that mines outside of the staking miner and that is up to you to allow to run by unlocking your wallet with BWK to stake.

**Comment by nunyabiddensss** [comment]
@dustinengle Many thanks for taking the time to explain. I understand. Cheers
