### ISSUE TITLE
ubuntu bulwarkd doesnt boot

### ISSUE THREAD

**Issue by bobozm** [bulwark-crypto/Bulwark#20]
Bulwarkd will not resync when server is rebooted

**Comment by orpenk** [comment]
root@vultr:~# ls
bulwark-1.2.0  Bulwark-MN-Install
root@vultr:~# cd bulwark-1.2.0
root@vultr:~/bulwark-1.2.0# ls
bin
root@vultr:~/bulwark-1.2.0# cd bin
root@vultr:~/bulwark-1.2.0/bin# ls
bulwark-cli  bulwarkd  bulwark-qt  bulwark-tx
root@vultr:~/bulwark-1.2.0/bin# bulwarkd
Bulwark server starting
root@vultr:~/bulwark-1.2.0/bin# bulwarkd: main.cpp:2303: bool ConnectBlock(const CBlock&, CValidationState&, CBlockIndex*, CCoinsViewCache&, bool): Assertion `hashPrevBlock == view.GetBestBlock()' failed.

**Comment by orpenk** [comment]
bulwarkd -reindex  -daemon 
seems to make it run after a server restart

**Comment by bobozm** [comment]
Ok thanks
