### ISSUE TITLE
bulwark-qt size

### ISSUE THREAD

**Issue by baliwae** [bulwark-crypto/Bulwark#29]
the size of official binary wallet release for linux is too big. 
https://www.virustotal.com/#/file/2dd4fc838f3646c1a3de636090762c45573e14d5fb48a6485f02efe5a4f6daa6/detection

File size | 157.27 MB

it will better if the binary is stripped before with strip command.

it  try compile from source code, and run strip command to binary , and the size of qt wallet reduce to only 9 MB

**Comment by padraiq** [comment]
Agreed, someone forgot to strip, will be fixed soon

**Comment by kewagi** [comment]
@baliwae We've created a stripped version and uploaded it to the release page.
