### ISSUE TITLE
ubuntu16.04 version on Mint Sonya didńt work

### ISSUE THREAD

**Issue by michiel1972** [bulwark-crypto/Bulwark#32]
FYI: Tried to install bulwark-1.2.1.0-x86_64-ubuntu16.04-gnu.tar.gz on my Linux Mint (ubuntu 16.04) system.

Did not work. Nothing happens when executing.

Then I tried the bulwark-1.2.1.0-x86_64-ubuntu14.04-gnu.tar.gz . It worked.

Any ideas why the 16.04 didn't work on Mint Sonya?

**Comment by kewagi** [comment]
We have a new universal build now in 1.2.2, could you please check if that works on Mint?

**Comment by michiel1972** [comment]
Yes, I updated with 1.2.2 and it works now fine on Mint Sonya.
