### ISSUE TITLE
Cannot build in Ubuntu

### ISSUE THREAD

**Issue by shwuhk** [bulwark-crypto/Bulwark#35]
When running ./configure, it seems wrongly detect SSL library which is installed with LibreSSL.
```
checking for EVENT_PTHREADS... yes
checking for ZMQ... yes
checking for RAND_egd in -lcrypto... no
configure: error: Detected LibreSSL: This is NOT supported, and may break consensus compatibility!
```

I googled it and find somebody is also experiencing this and have a fix. Can you please take a look and fix it? Thanks.

https://github.com/PIVX-Project/PIVX/issues/149
https://github.com/PIVX-Project/PIVX/pull/447

**Comment by kewagi** [comment]
Thanks for the links, we'll look into it. In the meantime, you should be able to configure successfully if you run `export LD_LIBRARY_PATH="/path/to/openssl"` beforehand.

**Comment by shwuhk** [comment]
Finally, I downgraded the SSL library back to 1.0.2 in order to build. Anyway, thanks for your time

**Comment by dustinengle** [comment]
`
export LDFLAGS=-L/usr/local/opt/openssl/lib
export CPPFLAGS=-I/usr/local/opt/openssl/include
`

**Comment by Carbon-Zero** [comment]
I fixed it.
