### ISSUE TITLE
Inconsistent or inoperable behavior from 'multisend'

### ISSUE THREAD

**Issue by heartofgold42** [bulwark-crypto/Bulwark#4]
Multisend is a system where which users can select an address or address[es] to donate percentages of mined or minted coins.  It's unique to the PIVX ecosystem and comes from Hyperstake (HYP).  Either fix, implement new code, or disable.

**Comment by dustinengle** [comment]
Issue fixed in current release and needs to be closed.
@padraiq @bulwark-crypto
