### ISSUE TITLE
Minor spelling mistake

### ISSUE THREAD

**Issue by SHTDJ** [bulwark-crypto/Bulwark#41]
Minor mistake in line 265 of https://github.com/bulwark-crypto/Bulwark/blob/master/build-aux/m4/ax_boost_base.m4.

![image](https://user-images.githubusercontent.com/36552562/37572283-1810a21c-2b09-11e8-831f-2a3dd903e874.png)

**Comment by KaneoHunter** [comment]
#45 Fixed.
