### ISSUE TITLE
Wallet not working

### ISSUE THREAD

**Issue by 2017monster2017** [bulwark-crypto/Bulwark#48]
As a user,  I want to ask some help fixing the wallet installation, even version 1.2.3 is not opening and I dont know where are my coins now. 

*Type*: Bug

- Open Bulwark
- error opening the wallet.... and error again.
Thanks

**Comment by KaneoHunter** [comment]
Hello,

Do you have an error message and any screenshots?

**Comment by 2017monster2017** [comment]
Hi,
Yes,  please see attached the 2 errors.
Thanks

**Comment by KaneoHunter** [comment]
Your attachments are not appearing on Github, can you come speak to us in Discord about your issue?

https://discord.gg/VnqxG6U
