### ISSUE TITLE
Multi-signature Isn't Functional

### ISSUE THREAD

**Issue by KaneoHunter** [bulwark-crypto/Bulwark#72]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to create a multisig wallet without needing the public key to be in my own wallet.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: When attempting to make a multisig wallet, my address returned with no errors, however, the 3rd part address returned "no full public key for address...". The 3rd part then attempted the same but my address returned the same error. I also tried adding the 3rd party's address as a watch-only address but this also did not work.

Having given the code a brief look, I could be wrong, but I believe that the code [here](https://github.com/bulwark-crypto/Bulwark/blob/master/src/qt/multisigdialog.cpp#L734):

```  #ifdef ENABLE_WALLET
            // Case 1: Bulwark address and we have full public key:
            CBitcoinAddress address(keyString);
            if (pwalletMain && address.IsValid()) {
                CKeyID keyID;
                if (!address.GetKeyID(keyID)) {
                    throw runtime_error(
                        strprintf("%s does not refer to a key", keyString));
                }
                CPubKey vchPubKey;
                if (!pwalletMain->GetPubKey(keyID, vchPubKey))
                    throw runtime_error(
                        strprintf("no full public key for address %s", keyString));
                if (!vchPubKey.IsFullyValid()){
                    string sKey = keyString.empty()?"(empty)":keyString;
                    throw runtime_error(" Invalid public key: " + sKey );
                }
                pubkeys[i++] = vchPubKey;
            }
```

Is checking for the full public key in the wallet, which negates the whole purpose of multisig if one user has all the keys anyway.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
I believe that the expected behavior is that you would be able to make a multisig address without needing all private keys involved.
#### Actual behavior
[comment]: # (Describe what actually happened.)
The actual behavior is that you need all private keys involved to make the multisig address.
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Bulwark
- File>Multi-signature creation
- Enter a public address from your own wallet, and a address from a 3rd party's wallet
- Do the same on the 3rd party's wallet
- Both will reject the other wallet's address

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

I'm unsure as to what you would do to fix this.

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Bulwark version: 1.2.4.0
* Operating System: Windows

#### Logs

Debug file download link: https://instant.io/#0b55cc05519c65a79add0e30c20fc06014cf3c1b

**Comment by KaneoHunter** [comment]
For reference, this is how Bitcoin handles multisig.

https://github.com/bitcoin/bitcoin/blob/af20f9b1d485582b8c8aa8294bac4f2c540246d2/src/rpc/util.cpp#L46

And here is PIVX's implementation.

https://github.com/PIVX-Project/PIVX/pull/278/commits/a20202d841675596c9380c9de0b14662d98552cd

Trying to offer what I can.

**Comment by SHTDJ** [comment]
You don't need all of the private keys to create a Multisig Address but you will need the public keys which can't be derived from a Bulwark Address. You can use the command validateaddress to get the public key of an address you own

**Comment by KaneoHunter** [comment]
In which case I think we should add clearer instructions to the window, that the 3rd parties need the hex versions of their public keys. This would offer a huge benefit to user experience for less technical people.

I'll make a PR shortly with some ideas for better instructions.

**Comment by KaneoHunter** [comment]
So to summarise, all the features (creating addy, creating transactions, and signing) _do_ work, but could use some clearer instructions or a nice guide. I'll put this together myself and submit it for review.
