### ISSUE TITLE
Containerized/Virtualized TOR nodes

### ISSUE THREAD

**Issue by heartofgold42** [bulwark-crypto/Bulwark#9]
Create Docker/LXC/KVM containers that provide a user friendly way to start up an onion routed TOR full node or masternode.  This will allow users a higher level of privacy and strengthen our TOR network.  Making this process more accessible to those who might otherwise not have the expertise to set this up.

- https://blog.jessfraz.com/post/routing-traffic-through-tor-docker-container/
- https://blog.jessfraz.com/post/running-a-tor-relay-with-docker/
- https://blog.jessfraz.com/post/tor-socks-proxy-and-privoxy-containers/
- https://www.whonix.org/wiki/KVM

**Comment by dustinengle** [comment]
Closing as I believe this is already done.
